### ISSUE TITLE
Binding to local connection/interface address needed for web applications?

### ISSUE THREAD

**Issue by ClaesNilsson** [sysapps/tcp-udp-sockets#11]
Jonas: The question is what's the use case for, on a client side device, setting up a socket connection specifically from wifi, 3G or Bluetooth rather than the "default" connection?

Claes: All socket APIs I have seen provide the possibility to define the local address. Use Case examples to be given.

**Comment by ClaesNilsson** [comment]
Some use cases.

• A mobile device is acting as wifi hotspot. This means that both wifi and the mobile network is active. If an app wants to communicate through UDP or TCP with a device in the wifi network or send a UDP multicast on wifi then the socket has to be bound to the wifi address. This has to be explicitly stated as the mobile network is the “default interface”.
• Similar as above for a desktop computer having a LAN connection but wants to communicate with TCP or UDP to a device (e.g. a media device) in the local wifi network.
• An application running on a desktop computer that has two network cards wants to create a TCPServerSocket using one of the interfaces (which may not be the “default” one).

**Comment by ClaesNilsson** [comment]
Can I close this issue?

**Comment by sicking** [comment]
In all of those use cases, it more sounds like the author wants to specify a local network interface rather than a local IP number?

**Comment by anotherlin** [comment]
Yes, IP number is not really relevant, but the correct interface is.

**Comment by ClaesNilsson** [comment]
Closed as discussion continues in https://github.com/sysapps/raw-sockets/issues/24.
