### ISSUE TITLE
Use Cases and Requirements

### ISSUE THREAD

**Issue by ClaesNilsson** [sysapps/tcp-udp-sockets#14]
Dave Raggett proposes that each SysApps specification should contain a section describing the use cases and requirements.

A short list of use cases for the Raw Socket API is here: http://www.w3.org/wiki/System_Applications_WG:_Raw_Sockets_API

**Comment by ClaesNilsson** [comment]
I haven't seen use cases and requirements in any other SysApps specification so I am not sure if we should have that in the API specifications or if that should be stated elsewhere.

**Comment by marcoscaceres** [comment]
They should be in the spec. But we can add them incrementally.

**Comment by ClaesNilsson** [comment]
Ok, I will add this
