### ISSUE TITLE
Does an application have to join a multicast group even if it is only sending multicast messages.

### ISSUE THREAD

**Issue by ClaesNilsson** [sysapps/tcp-udp-sockets#16]
Currently the specification states in the description of the joinMulticastGroup() method:

"Note that even if the socket is only sending to a multicast address, it is a good practice to explicitely join the multicast group (otherwise some routers may not relay packets)."

Example 1 also illustrates this.

This wording is based on a comment from 4D. However, is there any documentation supporting this? I have for example found section 2.2 in http://www.tldp.org/HOWTO/Multicast-HOWTO-2.html that states the opposite, i.e. that an app does not have to join a muticast group if it just is sending multicast data.

**Comment by ClaesNilsson** [comment]
Any feedback on this issue from 4D or anyone else?

**Comment by anotherlin** [comment]
For sending, It's not mandatory to join the multicast group. But this is a good practice to join the group anyway, especially as a hint for routers.

**Comment by ClaesNilsson** [comment]
Ok, then I propose to keep the current wording in the specification.

Can I close this issue?
