### ISSUE TITLE
Introduce a permission in section 4, based on Runtime and Security spec

### ISSUE THREAD

**Issue by mounirlamouri** [sysapps/tcp-udp-sockets#21]
Otherwise, it is pretty unclear what is the security model of this API.

**Comment by ClaesNilsson** [comment]
Ok. Would a statement like below be ok?

"To use this API an application must state a request to get the permission to use the API in the application's manifest. The permission name for this API is raw-socket. See [Sysapps-Runtime]."

**Comment by marcoscaceres** [comment]
That's pretty much what I used for WAC also (see http://specs.wacapps.net/viewport/index.html#feature-string).

Just make sure "raw-socket" is wrapped in a code tag.
