### ISSUE TITLE
Join/leave group

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/tcp-udp-sockets#27]
Would it be possible to drop the word "Multicast" from joinMulticastGroup() and from the leave method? Seems redundant.

**Comment by ClaesNilsson** [comment]
For clarity reasons I think that we should keep "Multicast" in the names of these methods. This is common vocabulary for multicast support.

**Comment by marcoscaceres** [comment]
Right, but we don't support anything but Multicast (hence it being redundant). If we wanted to support more types, then we would end up with method names like: 

```
joinBarfooGroup()
joinFoobarGroup()
```

What would be nicer for the future (v2) is just: 

```
joinGroup(address, optional type)
```

Where type would default to `multicast` when missing, and other group types could be supported.

**Comment by ClaesNilsson** [comment]
I see your point of making this extensible. However, are there any other potential groups in addition to multicast groups? I am not aware of any.

**Comment by marcoscaceres** [comment]
Don't know :) But if there is not, then "multicast" doesn't need to be typed (as it's the only possible group)... and if there are, then the extension point will work for future group types in a backwards/future compatible way in future versions of the API. Hopefully that makes sense.

**Comment by sicking** [comment]
How about dropping "group" instead. I.e. joinMulticast() and leaveMulticast()?

I agree that there's currently redundancy in the name, but I think the "multicast" part is more descriptive than the "group" part is.

**Comment by marcoscaceres** [comment]
WFM :+1:

**Comment by ClaesNilsson** [comment]
Ok, I'll change to joinMulticast() and leaveMulticast()
