### ISSUE TITLE
UDPSocket constructor lacks error handling

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/tcp-udp-sockets#28]
The steps to construct a UDPSocket seems to be lacking error handling when checking options, etc. it also doesn't say what to do if it can't bind the socket.

**Comment by ClaesNilsson** [comment]
Doesn't step 3 describe the error handling when the UA can't bind the socket.

**Comment by ClaesNilsson** [comment]
Marcos, is this issue still live? I handle errors when constructing a UDP socket in the step "When the attempt to create a new UDP socket (readyState is "opening") has failed the user agent must run the following steps:"

**Comment by marcoscaceres** [comment]
I'm closing, as I agree all the bits are there... however, the spec will need a bit of work later to make sure all the bits are coherent. This will become a bit more obvious when writing the prototype reference implementation.
