### ISSUE TITLE
Constructing a UDPSocket must open it

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/tcp-udp-sockets#29]
The current algorithm sets the state to "opening", but doesn't explain how the socket gets to "open" and the open event is fired (or not, in case of an error).

**Comment by marcoscaceres** [comment]
Ok, found the "open" part. Please move that to the constructor section, it's confusing otherwise.

**Comment by ClaesNilsson** [comment]
If we compare with the Web Sockets specification the move from "connecting" to "open" is described separate from the description of the constructor (). See "5 Feedback from the protocol". Shouldn't we have a similar way of describing the sematics?

**Comment by anotherlin** [comment]
UDP sockets are connection-less, so they cannot be "opened" or "closed".  As long as the UDP socket constructor is successful, the UDP socket is "open". The "onopen" should occur (event queued) immediately. Same goes for closing, after a close(), the "onclose" is immediate. However the UDP socket doesn't have a "onclose" event (see the interface definition in section 5).

I think it is a good idea to have "opening" and "closing" states, along with "onopen" and "onclose" events. This makes thing more "symetrical" with TCP socket. Even if effects are immediate.

**Comment by anotherlin** [comment]
It would be great to add a note in constructor description and in close() description. It makes things more clear, even if other specs (websocket) are not that "pedagogical".

**Comment by marcoscaceres** [comment]
I'll leave this to the discretion of the Editor - but please aim always for legibility (the Web Socket spec is also hard to understand).

**Comment by ClaesNilsson** [comment]
Ok, I will try to clarify this. However, we may not need the 'open" event for UDP and TCP server sockets. This is still under investigation.

**Comment by ClaesNilsson** [comment]
Closing as these parts have been rewritten. Also referring to https://github.com/sysapps/tcp-udp-sockets/issues/44.
