### ISSUE TITLE
Send() address and port should be args

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/tcp-udp-sockets#31]
If address and port are required, then the should me arguments of send(), not options. Please only use options for optional things.

**Comment by ClaesNilsson** [comment]
I am not sure what you mean. If you are talking about UDP then default remote address and port could optionally be set by the constructor. This means that if remote address and port is omitted in the send() method the default remote address and port are used as destination. If no remote address and port arguments are given in the send() method and no default values were set by the constructor this is an error.
Could above be described differently in the specification?

**Comment by marcoscaceres** [comment]
I might return to this later, but send has already gone through some changes so this might not apply anymore. Hence, closing.
