### ISSUE TITLE
Could send() be a Future?

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/tcp-udp-sockets#33]
Looking at Example 3, the semantics of send() and onopen seem to fit the Future pattern, and may get rid of the catch-all exception.

**Comment by ClaesNilsson** [comment]
Maybe send() but if used with onopen they we would need to add a connect() method as a assume that a constructor can not return a Future object?

However, are there any benefits in using Future in this API?

**Comment by ClaesNilsson** [comment]
Closed as the discussion on using Promises occurs in https://github.com/sysapps/raw-sockets/issues/22.
