### ISSUE TITLE
Binding a socket to a local port when it is not specifically specified.

### ISSUE THREAD

**Issue by ClaesNilsson** [sysapps/tcp-udp-sockets#37]
[Patrick]

> - "bind the socket to any available randomly selected local port" - 
>   its not clear you want to say randomly here. Sometimes local ports are 
>   assigned sequentially according to availability.
> 
> 
> [Ke-Fong]: The intended meaning : Use standard behavior of socket, 
> bind to one of those ephemeral ports they way bind() does it when given port as zero.
> By "random", it rather meant let the system decide.

[Claes] Yes, this is basically what I mean so I will improve the wording here.

**Comment by anotherlin** [comment]
Then we can close this issue ?
