### ISSUE TITLE
Description of "loopback" attribute

### ISSUE THREAD

**Issue by ClaesNilsson** [sysapps/tcp-udp-sockets#38]
[Patrick]

> - I don't really understand the loopback attribute. What does it mean 
>   to set it to true but connect to 8.8.8.8? What does it mean to set it 
>   to false but connect to 15.15.15.15 which your OS has bound to the 
>   localhost interface? What purpose does it serve at all?
> 
> 
> [Ke-Fong]: Loopback is only relevant for UDP multicast.  A note should 
> be added about that.

[Claes] Yes, the use case for loopback is multicast. By setting the attribute the developer can define whether a sent multicast message should be received by yourself or not. I will clarify that this attribute is only applicable for multicast.

**Comment by anotherlin** [comment]
Can be closed too ?
