### ISSUE TITLE
HalfClose event

### ISSUE THREAD

**Issue by ClaesNilsson** [sysapps/tcp-udp-sockets#39]
[Patrick]

> - I don't understand the onHalfClose event.. how do you know if the 
>   server called half close or if it hung up completely? (they look the 
>   same on the wire)
> 
> 
> [Ke-Fong]: To "really" close a TCP connection, both peers have to 
> exchange FIN packets along with ACK packets.
> It is indeed impossible to know if the peer has called shutdown() or
> close() as both sends a FIN packet (which is part of the four steps 
> closing handshake).
> But in the case of shutdown(), the peer can still receive data but not 
> send, whereas close() kills its socket descriptor.
> Just imagine a client sending a single request to the server and then 
> doing a shutdown(), it can still read the answer of its request.
> This is a case allowed by TCP protocol (and probably well used), it 
> ought to be supported.
> 
> Indeed, a host never calling close() or halfclose(), will always 
> receive an "onhalfclosed" event instead of "closed". This can be 
> confusing.
> A "usage note" section and a state diagram of the possible states 
> along with transitions would be helpful for understanding.

[Claes] I am considering if we really need the onHalfClose event? Use cases:
1. A web app (Client) sends a request and expects a reply. Then the connection should be closed. So this means send() + halfclose(). The server ACKs the FIN and then sends the reply to the request that is ACKed by the Client. Then the Server sends FIN that is ACKed by the Client and the close event is issued to the web application.
2. A server sends FIN but the Client has more data in the send buffer. The Client ACKs the FIN, sends the data + FIN and issues the close event to the web application.

**Comment by anotherlin** [comment]
Half closed state makes no sense for TLS because there's the TLS record protocol running "under". So this state is never reached.

However for TCP, that state does exists and your two use cases are correct. 

Suggest that we keep onHalfClose event. We may add a note for end-user explaining all the subtleties.

**Comment by ClaesNilsson** [comment]
But looking at the two use cases above, when is the halfclose event issued?

There is currently no stepwise description for the halfclose event and I think that I made a mistake when I added this event to the TCPSocket. I can't see when i should be issued.

**Comment by anotherlin** [comment]
Both cases are half close. "half closed" = "One peer sent FIN to other. The other sent ACK, but hasn't sent (his) FIN". "closed" = "Both peers have sent FIN to each other and both have ACKed them".

First case, send() + halfclose() = client is "half closed". When server sends reply, then and only then, sends FIN + ACKed from client = "closed".
Second case, server is "half closed", even with FIN sent it can still receive.

As mentionned before (patrick), it is indeed very difficult to make difference between "closed" and "half closed".

**Comment by mcmanus** [comment]
I think you should remove the onHalfClose event. In a technical sense it is issued when a FIN has been received from the peer - and the presumption is the peer will not send anymore data but can still receive data. But in practice the peer has often done a full close() on his local socket and cannot receive data anymore either - sending more data to the peer will just result in a RST. TCP doesn't provide a way to distinguish those cases.

**Comment by anotherlin** [comment]
Well, seems that you guys are unanimous for the removal of the halfClosed state and event. 

In retrospect, the use cases for that feature should be rarely used now. So why not remove that indeed. It'll make things simpler for developer.

**Comment by ClaesNilsson** [comment]
Ok, I'll remove it!
