### ISSUE TITLE
Nagle algorithm/TCP_NODELAY

### ISSUE THREAD

**Issue by ClaesNilsson** [sysapps/tcp-udp-sockets#40]
[Patrick]

> - there doesn't seem to be any discussion of the nagle algorithm or a 
>   mapping to TCP_NODELAY anywhere in here and its an important topic for 
>   TCP applications. I would suggest that you provide a TCP attribute 
>   called sendCoalescing which defaults to false. Have the documentation 
>   point out that this corresponds to the nagle algorithm, which in most 
>   TCP APIs defaults to true/on, but because it is often the source of 
>   performance problems we have changed the traditional default.
>   Applications that do a lot of small sends that aren't expecting 
>   replies to each one (e.g. a ssh application) should enable nagle for 
>   networking performance but most applications will not want to. A bit 
>   more radically you could just disable nagle all the time without an 
>   attribute, but if you do that the API document should really mention 
>   it and the ssh client is an example of somewhere where such a config 
>   is not optimal.
> 
> 
> [Ke-Fong]: Ok, that needs to be addressed.

[Claes] So would it be enough to have an additional Boolean field in the TCPOptions dictionary (type of the TCPSocket constructor's options argument) stating nagle true/false with default set to false?

**Comment by mcmanus** [comment]
[Claes] So would it be enough to have an additional Boolean field in the TCPOptions dictionary (type of the TCPSocket constructor's options argument) stating nagle true/false with default set to false?

sgtm
