### ISSUE TITLE
Naming of API

### ISSUE THREAD

**Issue by ClaesNilsson** [sysapps/tcp-udp-sockets#42]
> - While we're talking nomenclature please don't use the term "raw"
>   anywhere in this document. That is a well known networking term and it 
>   doesn't mean access to TCP and UDP interfaces - this was brought up to 
>   me by several folks at the IETF meeting who were confused about the 
>   applicability of this spec because of the use of the term raw sockets.
>   (raw sockets generally give access to ethernet level framing in normal 
>   networking parlance) These are "transport level socket interfaces" or 
>   "tcp/udp sockets" or so on..
> 
> 
> [Ke-Fong]: I agree with you. "Transport level socket" would the most 
> appropriate term.

[Claes] Ok, yes I can see that "Transport level socket API" would probably be a better name but I guess that there will be many options on the appropriate name for this API :-).
However, "Transport layer socket API" is probably more correct as the OSI model defines protocol "layers", not "levels".

**Comment by anotherlin** [comment]
Seems we found the perfect name as "Transport layer socket API"  :)

**Comment by nickdesaulniers** [comment]
Or "[Standard Sockets](http://en.wikipedia.org/wiki/Raw_socket#Raw_sockets_vs_standard_sockets)?"

**Comment by ClaesNilsson** [comment]
I will change the name to Transport Layer Socket API when the next Public Working Draft is issued.

**Comment by marcoscaceres** [comment]
Argh... bikeshed city, but that's a hard name to remember and google. I like "Standard Sockets" ... ftw.

**Comment by ClaesNilsson** [comment]
But even though there is a definition in Wikipedia of "Standard Sockets", http://en.wikipedia.org/wiki/Raw_socket#Raw_sockets_vs_standard_sockets, is that really a term that people associate with UDP and TCP sockets?

**Comment by marcoscaceres** [comment]
Probably not... then lets just call it "TPC and UDP Sockets"

**Comment by AMorgaut** [comment]
I wonder if it would not be much simpler to separate UDP (User Datagram Protocol) and TCP (Transmission Control Protocol) which in fact are quite different, but "TPC and UDP Sockets" should work too. 

I must admit I liked the naming used for UDP by Microsoft in its .NET API usable in JavaScript as it is quite explicit:
-> [DatagramSocket Class](http://msdn.microsoft.com/library/windows/apps/br241319?cs-save-lang=1&cs-lang=javascript#code-snippet-1)
but maybe more people heard about UDP than Datagram.

**Comment by ClaesNilsson** [comment]
I can't think of anything that is clearer and makes people do the right assocation than one of the alternatives below:

TCP and UDP Socket API
or
UDP and TCP Socket API
or even shorter
UDP and TCP API

**Comment by marcoscaceres** [comment]
"TCP and UDP Socket API"

Nice and google-able :+1:

**Comment by ClaesNilsson** [comment]
Remains to change the short name. It is proposed to do that when the next publication takes place.

**Comment by domenic** [comment]
Sounds like this is settled, but just wanted to say thanks for choosing TCP/UDP instead of e.g. Net/Datagram. Node.js chose the latter and caused lots of unnecessary confusion.

**Comment by ClaesNilsson** [comment]
Fine :-)

**Comment by ClaesNilsson** [comment]
Fixed with https://github.com/sysapps/tcp-udp-sockets/pull/61
