### ISSUE TITLE
replace onopen -> onconnect, onclose -> onend

### ISSUE THREAD

**Issue by nickdesaulniers** [sysapps/tcp-udp-sockets#54]
to more easily allow for code reuse from [Node.js](http://nodejs.org/api/net.html#net_event_connect).

**Comment by ClaesNilsson** [comment]
Here we have a question whether naming in this API should be aligned with Web Sockets or with node.js.

**Comment by nickdesaulniers** [comment]
For context on why I filed this issue, I recently ported [node-irc](https://github.com/martynsmith/node-irc) to run in the browser runtime as opposed to the node.js runtime.  It's being used in [an IRC app for Firefox OS](https://github.com/nickdesaulniers/fxos-irc).  Creating a [shim](https://github.com/nickdesaulniers/node-irc/blob/master/lib/irc.js#L54-L60) was doable, but it would be much much easier to be able to drop in and reuse existing code from Node.js.

Having the same interface as websockets though is also beneficial.

**Comment by ClaesNilsson** [comment]
Not applicable any more as the API has been rewritten to be based on Streams.
