### ISSUE TITLE
Add ref to WHAT WG Streams API specification

### ISSUE THREAD

**Issue by ClaesNilsson** [sysapps/tcp-udp-sockets#60]
https://github.com/whatwg/streams

**Comment by marcoscaceres** [comment]
@ClaesNilsson I just realized that you can just reference [[!STREAMS-API]](even if it's out of date for now). @domenic and the other guys are looking to publish and updated version of the W3C spec that includes the WHATWG stuff. 

Just put a note in the "Status of This Document" section stating the above about Streams.

**Comment by ClaesNilsson** [comment]
Ok, I make such a note until the correct reference could be made.
