### ISSUE TITLE
How to handle UDP receive buffer getting full

### ISSUE THREAD

**Issue by ClaesNilsson** [sysapps/tcp-udp-sockets#66]
As UDP has no flow control mechanism the flow of datagrams can not be stopped if the application does not read out the datagrams fast enough or the sink in a pipe is to slow. Which is the best approach taking the ReadableStream buffer and it's high watermark into account?
- Stop copying things out of the kernel buffer when the high water mark is hit?
- Ignore that the high watermark is reached and just continue to fill the Streams API internal buffer until the memory limit is reached?
- more...?

**Comment by domenic** [comment]
> Ignore that the high watermark is reached and just continue to fill the Streams API internal buffer until the memory limit is reached?

This is usually how streams work, yeah. They are specifically designed to prevent losing data.

The "web socket stream" example at http://whatwg.github.io/streams/#rs-intro shows such a stream with no backpressure.
