### ISSUE TITLE
Rename ReadyState to SocketReadyState

### ISSUE THREAD

**Issue by schien** [sysapps/tcp-udp-sockets#68]
The ReadyState enum is not possible to be reused out side of Raw Socket API and will cause confusion since many APIs have their own 'readyState' attribute. Rename it to SocketReadyState will make the usage more clear.

**Comment by marcoscaceres** [comment]
Agree. It should be renamed.

**Comment by ClaesNilsson** [comment]
Even though the Web Socket API's readyState attribute currently is not an enum type it might be better to instead rename the TCP and UDP Socket API's ReadyState enum to TCPUDPReadyState in order to avoid any future confusion with Web Sockets. WDYT?

**Comment by schien** [comment]
It's clear for me to identify the usage if we choose `SocketReadyState` for Socket API (i.e. TCP & UDP socket API) and `WebSocketReadyState` for WebSocket API. IMO the term "socket" has been associate with TCP and UDP for a long time because of the POSIX socket API.

**Comment by ClaesNilsson** [comment]
Ok, thanks schien. I don't have a strong opinion so if there are no objections I'll change it to SocketReadyState.
