### ISSUE TITLE
Code line length too long for review

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/tcp-udp-sockets#7]
The current line length of the code in the HTML document makes this document really hard to review. Can you please run your code over [HTML5 Tidy](https://github.com/w3c/tidy-html5) or similar. For runtime spec, this is the config we are using:

https://github.com/sysapps/runtime/blob/gh-pages/tidyconfig.txt

We just do the following before doing a PR:

``` Bash
tidy -config tidyconfig.txt -o index.html index.html 
```

**Comment by ClaesNilsson** [comment]
I am using a windows machine and not sure how to build tidy on windows.
Build instructions on https://github.com/w3c/tidy-html5 are for
Linux.  However, I can always edit the source manually to fulfill the"Style
guide to contributors" that I see in other SysApps source documents.

Claes

2013/4/23 Marcos Caceres notifications@github.com

**Comment by marcoscaceres** [comment]
Someone compiled it for windows here: http://www.broerse.net/wordpress/2012/04/28/tidy-html5/

However, we can probably ask @draggett for help with building instructions for Win (as it's based off his original version).
