### ISSUE TITLE
The initial value of localPort and localAddress before UDPSocket.opened is resolved

### ISSUE THREAD

**Issue by schien** [sysapps/tcp-udp-sockets#70]
In the latest draft, UDPSocket is opened asynchronously but the localPort and localAddress is only realized after determine by platform if no initial value in constructor. I would suggest that these two attributes can be null before opened. This can be done by making localAddress and localPort nullable.

```
readonly    attribute DOMString?       localAddress;
readonly    attribute unsigned short?  localPort;
```

**Comment by ClaesNilsson** [comment]
Thanks for spotting this schien!
