### ISSUE TITLE
Allow to use domain name in remoteAddress

### ISSUE THREAD

**Issue by schien** [sysapps/tcp-udp-sockets#73]
Currently we only support IPv4/6 address for the remoteAddress, but I think it'll be useful for supporting domain name because it's been wildly used for addressing an Internet/Intranet service. In addition, many server are using Round-robin DNS for load balancing.
Otherwise, developers will have to use UDPSocket to manually do the DNS query to get the correct IP address before establish TCPSocket/UDPSocket to the real server.

**Comment by domenic** [comment]
Node.js solves this via a separate [DNS API](http://nodejs.org/docs/latest/api/dns.html). Ideally the web platform would expose that as well. But it is probably not worth blocking the usability of TCP/UDP sockets on that.

**Comment by ClaesNilsson** [comment]
Thanks for bringing this up schien. I am a bit puzzled that I haven't noted this issue before. Yes, it seems to be the right approach to allow the application to directly use a domain name/host name as remote address in the TCP and UDP API. So for TCPSocket the wording in step would be:

```
If the remoteAddress argument is not a valid hostname or IPv4/6 address and/or the remotePort argument 
is not a valid port number then throw DOMException "InvalidAccessError" and abort the remaining steps,
else set the mySocket.remoteAddress and mySocket.remotePort attributes to the requested values.
```

Ok?

**Comment by schien** [comment]
lgtm!

**Comment by ClaesNilsson** [comment]
For simplicity I think that I, for TCP, make the following definition:

```
remoteAddress of type DOMString, readonly
   The hostname or IPv4/6 address of the peer as stated by the remoteAddress argument in the 
   constructor.
```

and for UDP:

```
 remoteAddress of type DOMString, readonly, nullable
     The default remote hostname or IPv4/6 address that is used for subsequent send() calls.
     Null if not stated by the options argument of the constructor.
```

Then the stepwise descriptions could just use the term "address".

**Comment by ClaesNilsson** [comment]
Look good in https://github.com/sysapps/tcp-udp-sockets/pull/75?

**Comment by ClaesNilsson** [comment]
Fixed in https://github.com/sysapps/tcp-udp-sockets/pull/75 and issue closed.

**Comment by AMorgaut** [comment]
Just a note to say this approach I agree with is taking the direction of the proposal #17 (tagged as "later") of using directly dedicated URLs instead of separated addresses and ports
But of course this other one also requires to take care of the tcp & udp schemes
