### ISSUE TITLE
Rewriting TCPServerSocket to be consistent with current UDP and TCPSockets

### ISSUE THREAD

**Issue by ClaesNilsson** [sysapps/tcp-udp-sockets#77]
To be consistent with the current versions of UDP and TCP socket interfaces the following changes are proposed:
- Replace the `open` event and `onopen` EventHandler with an `opened` attribute of type Promise.
- Replace the `error` event and `onerror` EventHandler with a `closed` attribute of type Promise that is resolved with `undefined` if the TCPServer socket was closed cleanly, i.e. `close()` was called and rejected with `error` if the TCPServer socket was closed due to an error.
- Replace the `connect` event, `onconnect` EventHandler,  `connecterror` event and `onconnecterror` EventHandler with a method `listen()` that returns a Promise, which is resolved with a connected TCPSocket object and rejected if a connection attempt has failed.
- Let the `close()` method return the same promise as the `closed` attribute, "closedPromise".
- Remove ‘interface ConnectEvent’ (the Promise returned by `listen()` is resolved with the connected TCPSocket object directly and thus no `interface ConnectEvent` is needed). 
- Remove `interface SocketError` and use just DOMExceptions according to the specification for Promises. (Note, the reason for introducing `interface SocketError` was to have more granular machine interpretable error types than DOM error provided. However, error reporting is a general problem applicable to many specifications and a general solution has to be defined by W3C/WHAT WG.) 
- Update the example accordingly.

**Comment by domenic** [comment]
These changes sound like some really well-done promise usage. +1

On error types, I think (@annevk can correct me) that the best thing to do would be to pull-request them into https://github.com/heycam/webidl/.

**Comment by annevk** [comment]
Use `DOMException`. If you want custom names you can pull-request those into IDL. However, I typically find that JavaScript programs don't branch on errors so you probably want to design the API in such a way that if all errors were TypeError and not distinguishable it would still be usable.

**Comment by domenic** [comment]
> However, I typically find that JavaScript programs don't branch on errors so you probably want to design the API in such a way that if all errors were TypeError and not distinguishable it would still be usable.

I agree with this, but still think it is a shame to hide information (e.g. details of a failure) from the developer that would otherwise be available. It could be especially important for debugging, even if there is no runtime branching.

That said it speaks to how this is potentially non-urgent and could wait on us getting our act together on adding such information to errors generally.

**Comment by annevk** [comment]
Note that even if everything was `TypeError`, browser vendors would still provide usable error messages for each of them. That only gets problematic if you want to do remote debugging and browser vendors have localized the messages.

**Comment by ClaesNilsson** [comment]
Thanks for your responses Domenic and Anne!  I will make the changes to the TCPServerSocket. Then I will go through specification on error handling to see if I need to submit any additional error types to https://github.com/heycam/webidl/.
