### ISSUE TITLE
Controlling TCP Keepalive

### ISSUE THREAD

**Issue by asutherland** [sysapps/tcp-udp-sockets#80]
https://github.com/sysapps/tcp-udp-sockets/blob/27dfc6fb82aa39d2d8edb97f0ecf6380f20557ad/oldBerkeleyStyleVersion/index.html#L411 included support for setting a TCP keepalive timeout, but the new streams draft does not seem to cover this.

It's worth noting that the Linux TCP stack actually has 3 knobs (do man 7 tcp and search on the things at the start of the bullet point for the /proc interfaces and the things in parens at the end for the TCP socket options):
- tcp_keepalive_time: How long the connection has to have been idle in seconds. (TCP_KEEPIDLE)
- tcp_keepalive_probes: How many probes to send out without having heard anything before we assume the other side is dead. (TCP_KEEPCNT)
- tcp_keepalive_intvl: At what interval do we send those probes?  It's not clear if this is also intended to be the amount of time we should wait for the ping to come back or not. (TCP_KEEPINTVL)

**Comment by ClaesNilsson** [comment]
Sorry for late reply Andrew. 

Yes, this option was present in the first, Berkeley-style, version of the API and I see that it was dropped in the later versions. Unfortunately I don't remember the rationale for this. Maybe it was considered to be a too level option to set for web applications and the default values for be sufficient. However, I see no problem of adding this as a new field,  "tcpKeepAliveOptions", in dictionary TCPOptions. The type of "tcpKeepAliveOptions" could be another dictionary:

```
dictionary TCPKeepAliveOptions {
    boolean                      keepAliveEnabled;
    unsigned long            tcpKeepAliveTime;
    unsigned short           tcpKeepAliveProbes;
    unsigned short           tcpKeepAliveIntvl;
};
```

**Comment by asutherland** [comment]
Yes, that makes sense and seems desirable.  Thanks!

It is pretty low level, but at least for cases like IMAP using IDLE/NOTIFY where the connection can be inactive for ~30 minutes, it's potentially nice if connection loss is detected more promptly and the OS is given a chance to try and be more efficient about it.  And internally, Firefox/Gecko/Necko does set the keep-alives to be much more aggressive than the defaults for HTTP(S) connections.

My only, likely redundant, suggestion would be to make sure the units are documented since the option names aren't self-describing in that way.

**Comment by ClaesNilsson** [comment]
Ok, if there are no objections I'll add this to the specification. I will include units and default values.

**Comment by ClaesNilsson** [comment]
Sorry for the delay. The PR is https://github.com/sysapps/tcp-udp-sockets/pull/85. Looks ok ? @asutherland

**Comment by asutherland** [comment]
Thanks for the changes!  Maybe the description of `States the "keepalive" options for the TCPSocket. If this field is omitted keepalive probes will not be sent.` could instead be something more like `Requests "keepalive" options for the connection, subject to adjustment by the system for power-saving or efficiency purposes. If the field is omitted, system defaults will be used.`

My rationale is that:
- There are some values that are arguably silly/wasteful, like sending a keep-alive after 1 second and then sending 1 keep-alive packet per second and the system should be able to override these to choose something more sane.
- It's possible for there to be situations where the system knows with high confidence that the network is stable (but perhaps expensive?) and therefore that aggressive keepalives are not needed, and therefore can be reduced.
- The TCP stack will always set some values for this, so it's not totally accurate to say that no keepalive will be used.  (Although the linux defaults are so conservative that they nearly count as not being used!)
- The benefit of the current approach is that we're not adding baggage to the spec by creating some new concept that then needs to be reflected into what the platform actually provides.  It's easy to implement without a ton of thought.  But really the two things a caller might be saying with the values they provide are "I really want this connection to stay alive, please help me do that without having to periodically send high level data myself" or "I don't really care about this connection staying alive, let's save the bandwidth".  If an implementation wants to go to the trouble to figure out how to better address those desires, the new phrasing I think more clearly allows them to infer the desire and set the settings appropriately.
- The driving use-case for me was an email app on Firefox OS where we kept ending up with a lot of useless zombie-like connections.  Our solution was just to aggressively drop idle connections, but it would have been nice to be able to get the system to be more reliable about telling us when connections were dead.

One possible nit would be that Intvl could be Interval, but since we're just reflecting the linux TCP stack, there's an argument to be made for using it as-is as you have done.  (Search engines are more likely to match them up, etc. etc.)

**Comment by ClaesNilsson** [comment]
Thanks for your Andrew. What you say makes sense and I will change the wording of the description according to your suggestion. 

For the individual options I used the Linux defaults but I may make some changes?

`keepAliveEnabled`: You state 
`The TCP stack will always set some values for this, so it's not totally accurate to say that no keepalive will be used. (Although the linux defaults are so conservative that they nearly count as not being used!)`. Which is your suggestion, should I keep the default that the "keep-alive" is off or should the default be implementation dependent?

`tcpKeepAliveIntvl`: Default 75 seconds ok?

`tcpKeepAliveProbes`: I stated default 8 but I see Linux uses 9. Is that ok?

`tcpKeepAliveTime`: Linux states 2 hours which is, as you say, very conservative. Do you suggest another default or should we refrain from specifying it and leave it implementation dependent?

Should we maybe refrain from specifying defaults for all options and leave that implementation dependent?

**Comment by asutherland** [comment]
I've made a post on Mozilla's dev.tech.network list to try and get some feedback from people with more expertise with TCP keep-alive settings at https://groups.google.com/forum/#!topic/mozilla.dev.tech.network/mZktKtvYj_M

But if no one shows up, I think your proposal that we just leave everything implementation dependent, especially defaults, is the right course of action.  My desire with this request was to make sure applications had a way to tweak the value, but given that I don't think either of us really know the right answer, I think leaving implementations maximum latitude is probably the way to go.

I also just checked the Chrome browser's add-on API at https://developer.chrome.com/apps/sockets_tcp#method-setKeepAlive and they just take enabled/disabled (presumably controlling whether to set SO_KEEPALIVE on the socket for linux) and the delay before sending the probes (presumably mapped to tcp_keepalive_time for linux).

**Comment by asutherland** [comment]
There's been great feedback at https://groups.google.com/forum/#!topic/mozilla.dev.tech.network/mZktKtvYj_M already, and I've asked a follow-up question there about a potential simplification based on the feedback.  Please do feel free to comment there too if you're so inclined!

**Comment by ClaesNilsson** [comment]
Ok, thanks Andrew. I checked https://groups.google.com/forum/#!topic/mozilla.dev.tech.network/mZktKtvYj_M and that provides good input. It is clear that different users of TCP have need different keep-alive strategies so it is good to provide the option to impact this in the API. However, it is a question how complicated we should make it. The current proposal for  TCPKeepAliveOptions does not make it possible to define a strategy like:
`1st minute: ping every 10s 
Subsequently: ping every 10mins`

So could we make it simple. You state `I've asked a follow-up question there about a potential simplification based on the feedback` but I can't see your follow-up question.

**Comment by asutherland** [comment]
Unfortunately it got stuck in some type of moderation queue (the Mozilla maliling list setup can unfortunately be quite troublesome, especially if one is trying to avoid fully subscribing).  Here's what I wrote. Hopefully it shows up soon, if not, I'll try and re-send more appropriately soon:

Yes, I've been following that bug and am very optimistic about it improving things for us!  Our exemplar horrible failure was people wandering around the MoCo SF office, using the elevator, etc. and presumably resulting in various handoffs between wi-fi and cellular, but with cellular in the elevator probably not working so great.  People were usually dogfooding on flame devices or similar non-production devices (nexus4/5) that probably used mozRIL.

Things were confusing, however, because in the many partner QA bugs filed (presumably all with not-mozRIL since they usually weren't Tarako), the system seemed proactive about closing connections on most network handoffs.  (The bugs were filed about SMTP sends failing because the connection got killed when this would happen.)

Patrick, the specific advice about pipelining NOP's and doing application level timeouts is particularly helpful, thank you!  IMAP does have a NOOP too.  The potential wrinkle in all cases is that "push email" is in general a lie and just involves an HTTPS long poll (ActiveSync) or otherwise just leaving a TCP connection open and listening (IMAP).  But keep-alive isn't going to save us from much but forgetful NATs there now that we have better transition notifications.  The good news is that JMAP (http://jmap.io/) may improve this situation for the mail providers who care by eventually supporting things like simple-push notifications, unfortunately many don't.

In terms of https://github.com/sysapps/tcp-udp-sockets/issues/80, if I were to distill these comments down, would a reasonable proposal be to collapse the support down to the few profiles that we know we use and not support anything else?
- Off:  Don't use TCP keep-alives.
- Frequent-then-sparse: Keep-alive every 10s for first minute, then every 10 minutes after that.
- Sparse: Every 10 minutes.

Or would one go so far as to say we don't need keepalive at all? 

Thanks very much all for the high quality feedback with super-fast turnaround!

**Comment by ClaesNilsson** [comment]
Thanks for copying your input to Mozilla's dev.tech.network list here. What you propose is simple but it might be too limiting. However, let us see the response to your input (Unfortunately I can't still see your input at https://groups.google.com/forum/#!topic/mozilla.dev.tech.network/mZktKtvYj_M and any potential replies so please provide me feed back here instead.)

**Comment by ClaesNilsson** [comment]
Would like to close this. In order to make it a bit more flexible but still keeping it simple, what about?:
- Off:  Don't use TCP keep-alives.
- Frequent-then-sparse: Keep-alive probes every 10s for first minute, then send with "SparseInterval" after that.
- Sparse: Sent with "SparseInterval".
- SparseInterval: The time (in seconds) between individual keepalive probes . Default is 600 seconds (10 minutes).

**Comment by asutherland** [comment]
Sounds great.

**Comment by ClaesNilsson** [comment]
Updated PR https://github.com/ClaesNilsson/raw-sockets/commit/1d57e070b086e26f51a69f8a44aba95c04b44189 

Any more comments Andrew or anyone else before I merge?

**Comment by ClaesNilsson** [comment]
Closed with https://github.com/sysapps/tcp-udp-sockets/pull/85
