### ISSUE TITLE
Implementation status (even if experimental)?

### ISSUE THREAD

**Issue by dmitshur** [sysapps/tcp-udp-sockets#88]
Hi, sorry for the noise, but I've looked through issues carefully and searched Google quite hard, and I wasn't able to find an answer to this question, that's why I'm resorting to opening an issue here.

I wanted to know if there any updates on the implementation status of this API, and/or expected dates when it might start appearing?

For example, does Chrome browser implement this yet? Maybe Canary version with experimental flag turned on? Or is that not the case yet?

I realize this is a draft of a specification, but it seems to have existed since as early as 2012, and given that much time has passed, I thought there's a chance of seeing some initial implementations by now.

Thank you!

**Comment by ClaesNilsson** [comment]
Hi,

The implementations that I am aware of are:
- Crosswalk experimental: https://crosswalk-project.org/documentation/apis/web_apis.html. Even though this web site points to a version of the API that has been adapted to be based on the Streams API I believe that Crosswalk implemented the old non-stream version.
- Firefox OS: Here the TCP and UDP Socket API (or the older name Raw Socket API) is referred for the UDP Socket API implementation: https://bugzilla.mozilla.org/show_bug.cgi?id=745283.  However, I don't know how much Mozilla follows this specification in their implementation.

Note that we are in the process of moving this specification to a Community Group. See https://bugzilla.mozilla.org/show_bug.cgi?id=745283. The current status of the API is stated here: https://lists.w3.org/Archives/Public/public-sysapps/2015Apr/0001.html. 

BR

**Comment by dmitshur** [comment]
Thanks for the information!

Feel free to close this issue, since you've answered my question.

**Comment by dmitshur** [comment]
For posterity, I was able to reproduce what's described in https://bugzilla.mozilla.org/show_bug.cgi?id=745283#c230, namely with Firefox developers edition (v40) and the dom.udpsocket.enabled flag set to true, I [could send a UDP packet](https://twitter.com/shurcooL/status/605218976969261056) from the dev console (of a new tab page).
